language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
sudo: false
#script: mvn clean verify
notifications:
  email:
    - krisnyb@stud.ntnu.no


#script: "mvn cobertura:cobertura -B"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ce6c8225-9b63-43d1-b59a-161d61f0e067